### ISSUE TITLE
One of the two Mohamed Al-Tablawi recitations is 404

### ISSUE THREAD

**Issue by mustafa0x** [quran/audio.quran.com#106]
https://quranicaudio.com/quran/89 is 404 while https://quranicaudio.com/quran/91 works.

**Comment by ahmedre** [comment]
interesting - it works for me so that means one of the servers must be 404-ing. if it still happens for me, can you send me the ip of the box? otherwise i'll try them all in sha' Allah.

**Comment by mustafa0x** [comment]
Are you sure it's working? It's a clear 404: https://download.quranicaudio.com/quran/mohamed_al-tablawi/001.mp3

That folder isn't even present: https://download.quranicaudio.com/quran/

**Comment by ahmedre** [comment]
fixed, jazakumAllah khairan - removed the extra one. sorry it took 3 years and change 😞
