### ISSUE TITLE
Send cache headers

### ISSUE THREAD

**Issue by mustafa0x** [quran/audio.quran.com#107]
Nginx config:
```
location ~* \.mp3$ {
    expires 1y;
}
```

I use this on muqri.com and have noticed that it makes a pretty big impact, especially when replaying old stuff. I can turn off all network and play files that have been played before.

It adds two headers to the response:
```
Cache-Control: max-age=31536000
Expires: Sat, 25 May 2019 01:13:32 GMT
```

**Comment by sabeurthabti** [comment]
@mustafa0x can't we achieve the same by adding the cache headers on the mp3 endpoint ? 
https://github.com/quran/audio.quran.com/blob/master/api/routes/audio_files.js#L17

**Comment by mustafa0x** [comment]
Probably; not that familiar with Express.

> I don't know if we are using nginx ?

Well, one of the server's response headers is `server: nginx/1.10.3 (Ubuntu)`, as I assume so. :)

**Comment by sabeurthabti** [comment]
Okay I will add the cache header and see how it goes.

**Comment by sabeurthabti** [comment]
cc @ahmedre  - is this something we can look into ?
I will raise a pr and do the cache headers on our side but nginx might be a better strategy.

**Comment by ahmedre** [comment]
sure i'll take a look in sha' Allah

**Comment by ahmedre** [comment]
jazakumAllah khairan for reporting this and should be fixed now.

before:

```
curl -I --head https://download.quranicaudio.com/quran/sa3d_al-ghaamidi/complete/001.mp3
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Sat, 09 Jun 2018 13:28:18 GMT
Content-Type: audio/mpeg
Content-Length: 1511552
Last-Modified: Mon, 16 Jun 2014 18:49:08 GMT
Connection: keep-alive
ETag: "539f3c24-171080"
Strict-Transport-Security: max-age=31536000
Accept-Ranges: bytes
```

after:
```
❯ curl -I --head https://download.quranicaudio.com/quran/sa3d_al-ghaamidi/complete/001.mp3
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Sat, 09 Jun 2018 13:32:00 GMT
Content-Type: audio/mpeg
Content-Length: 1511552
Last-Modified: Mon, 16 Jun 2014 18:49:08 GMT
Connection: keep-alive
ETag: "539f3c24-171080"
Expires: Sun, 09 Jun 2019 13:32:00 GMT
Cache-Control: max-age=31536000
Strict-Transport-Security: max-age=31536000
Accept-Ranges: bytes
```

also did on mirrors.quranicaudio.com, verses.quran.com, and some others.

**Comment by sabeurthabti** [comment]
thanks @ahmedre & @mustafa0x
