### ISSUE TITLE
Website not working 502 Bad Gateway

### ISSUE THREAD

**Issue by validity-check** [quran/audio.quran.com#140]
The website does not work as of now. I tested this on Firefox, Widows 10 and Android, Chrome. This is what I am given:
![image](https://user-images.githubusercontent.com/63739210/83978174-99dfe180-a8fd-11ea-9a64-150c1cc5604b.png)

**Comment by ahmedre** [comment]
jazakAllah khairan - fixed. will add this to the uptime checker to watch it for the future in sha' Allah.
