### ISSUE TITLE
All surah runtime/lengths show as the same length

### ISSUE THREAD

**Issue by tawfiqh-sray** [quran/audio.quran.com#146]
All surah runtime/lengths show as the same length. e.g Surah Al-Baqarah shows as "01:39:32" for all reciters.

<img width="1162" alt="Screenshot 2020-11-27 at 09 14 15" src="https://user-images.githubusercontent.com/74904684/100432072-f80da600-3090-11eb-8403-bedd19e80b21.png">
<img width="1206" alt="Screenshot 2020-11-27 at 09 14 03" src="https://user-images.githubusercontent.com/74904684/100432082-f9d76980-3090-11eb-914e-c31ce91ba50a.png">
<img width="1181" alt="Screenshot 2020-11-27 at 09 13 57" src="https://user-images.githubusercontent.com/74904684/100432084-fa700000-3090-11eb-94a2-1285efc8b0f3.png">

**Comment by ahmedre** [comment]
fixed, jazakumAllah khairan
