### ISSUE TITLE
Audio durations not matching up.

### ISSUE THREAD

**Issue by TechStudent11** [quran/audio.quran.com#156]
Asalamu Aleykum. So I was on this site trying to listen to a surah. Pretty simple, right? But then I noticed something about the durations. They weren't matching up. Look at the screenshot below:
![screenshot](https://user-images.githubusercontent.com/76978184/117979598-15fa5a80-b301-11eb-8642-061a90b2c623.png)
As you can see, the audio player has the correct duration while the duration on the preview (I guess we could call it that??????) is smaller than the actual duration. API issue?

**Comment by wallid** [comment]
I've noticed the same. I'm currently setting it up locally. I will try give this a go.

**Comment by sabeurthabti** [comment]
Thanks for raising this issue, we're a community fo volunteers. Can I help you try to debug this issue and maybe submiit a fix? Many thanks

**Comment by TechStudent11** [comment]
Sure, I could try but I'm a Python person and your API is written in Ruby (I think).

**Comment by ahmedre** [comment]
wa3laikum alsalam,
this might actually be a data issue since these times are in the database today.
we should be able to re-run the script to get the correct timings.
walsalam 3alaikum.

**Comment by TechStudent11** [comment]
@ahmedre Asalamu Aleykum. Database problem huh? Oh well. Let me know when the fix is up and I'll close the issue.

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
fixed, jazakumAllah khairan

**Comment by wallid** [comment]
Thanks - it works now :)
