### ISSUE TITLE
Problem with Qari Maher al-Muaiqly

### ISSUE THREAD

**Issue by RagibHasin** [quran/audio.quran.com#159]
Actual links to the audio files are `https://download.quranicaudio.com/quran/maher_almu3aiqly/year1440/<SURAH_NO>.mp3` but UI is configured for `https://download.quranicaudio.com/quran/maher_almu3aiqly/year1440<SURAH_NO>.mp3`.

Notice the last backslash.

Jazzakumullah.

**Comment by ahmedre** [comment]
jazakumAllah khairan - will fix in sha' Allah

**Comment by ahmedre** [comment]
fixed, jazakumAllah khairan
