### ISSUE TITLE
Problem with Adel Kalbani (Taraweeh 1437H)

### ISSUE THREAD

**Issue by RagibHasin** [quran/audio.quran.com#161]
Assalamu 'Alaykum waRahmatullah.

Actual links to the audio files are `https://download.quranicaudio.com/quran/adel_kalbani_taraweeh_1437/<SURAH_NO>.mp3` but UI is configured for `https://download.quranicaudio.com/quran/adel_kalbani_1437/<SURAH_NO>.mp3`.

Maybe you have renamed the folder on server-side but have forgotten to update the UI?

Jazzakumullah.

**Comment by ahmedre** [comment]
wa3laikum alsalam wa ra7matullahi wa barakatuh,
nice catch - jazakumAllah khairan, fixed.
walsalam 3alaikum
