### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by sabeurthabti** [quran/audio.quran.com#3]
Keeping in-line with quran.com, we should implement a search function.

**Comment by mmahalwy** [comment]
@sabeurthabti I am thinking since the data is very very limited, search can be implemented via redux-search: https://treasure-data.github.io/redux-search/

**Comment by sabeurthabti** [comment]
@mmahalwy Yeah sounds good

**Comment by sabeurthabti** [comment]
Probably won't be useful since we have a limited amount of reciters. Closing until data grows.
