### ISSUE TITLE
missing alternate recitations

### ISSUE THREAD

**Issue by ahmedre** [quran/audio.quran.com#52]
many reciters had alternate recitations that were shown on the old site. these are no longer there. they should all be there under the main qari (i.e. off the qaris page).

**Comment by ahmedre** [comment]
btw, these are all in the database, they just need to be surfaced... example:

```
audio_quran=# select id,name,home from qaris where name like 'Hatem%';
 id |            name             | home
----+-----------------------------+------
 85 | Hatem Farid                 |    1
 86 | Hatem Farid - Taraweeh 1432 |
 87 | Hatem Farid - Taraweeh 1431 |
 96 | Hatem Farid - Taraweeh 1433 |
(4 rows)


audio_quran=# select * from related where qari=85;
 qari | related
------+---------
   85 |      86
   85 |      87
   85 |      96
(3 rows)
```

just need to add an endpoint in the api if one isn't already there.

**Comment by ahmedre** [comment]
on the bright side, if you know the id, the page does properly load - ex:
http://quranicaudio.com/quran/86

that's the expected behavior (these links are only reachable from the "main qari's" page).

**Comment by sabeurthabti** [comment]
Okay sounds good, in terms of design how should we represent these related qaris? Maybe above the the Play All button on the qari page?

**Comment by ahmedre** [comment]
sure, or on the side - here's an example:
http://legacy.quranicaudio.com/quran/85
