### ISSUE TITLE
End-less Recritation

### ISSUE THREAD

**Issue by sabeurthabti** [quran/audio.quran.com#6]
Should transition to the next surah after the selected one has completed.

**Comment by mmahalwy** [comment]
+1

**Comment by atalebagha** [comment]
I'll take a stab at this

**Comment by sabeurthabti** [comment]
@atalebagha I think I solved this in my PR for the new designs #7.

**Comment by mmahalwy** [comment]
+1

**Comment by sabeurthabti** [comment]
done based on a the 'play all' feature. Closing.
