### ISSUE TITLE
Playing surah for qari A shows as playing when on qari B page

### ISSUE THREAD

**Issue by mmahalwy** [quran/audio.quran.com#65]
STR:
- Go to Qari A (anyone)
- Click Surah 2 to play
- While playing, I go to another Qari (Qari B)
- Shows it is playing Surah 2 in the list. I cannot click to play that Surah for Qari B.

**Comment by sabeurthabti** [comment]
@mmahalwy This has been fixed on beta.quranicAudio.com

**Comment by mmahalwy** [comment]
Ah, nice :) Didn't notice

Thank you!
