### ISSUE TITLE
horizontal scroll on listening page

### ISSUE THREAD

**Issue by ismailfarooq** [quran/audio.quran.com#90]
there is scroll on https://quranicaudio.com/quran/5 page please fix it by removing negative margin on line no 5354 and 5355 in public/main-c6367f480f98ef701275.css

**Comment by sabeurthabti** [comment]
Salam @ismailfarooq as you know this is an open source project. Is there anything I can do to help you contribute this fix? 

Come join us on https://quranslack.herokuapp.com

**Comment by ismailfarooq** [comment]
w.salam @sabeurthabti i have joined the community but couldn't find any channel.
