### ISSUE TITLE
Typo in "recritation"

### ISSUE THREAD

**Issue by aam1r** [quran/audio.quran.com#97]
Should be "recitation" instead

https://github.com/quran/audio.quran.com/blob/2b69ec7aabd697700f7a06b90d3add0ae2d94383/src/containers/Qari/index.js#L75

https://github.com/quran/audio.quran.com/blob/1c7d34be6aa6c3ce01ad0e059ccbd6a47b26614d/src/config.js#L31

![typo](https://user-images.githubusercontent.com/566418/32797072-9bea9fb6-c93e-11e7-9d08-dfc2704a4b8e.png)

**Comment by mmahalwy** [comment]
@aam1r good catch! Mind putting out a PR for it?
