### ISSUE TITLE
the main website has horizontal scrolling problem .

### ISSUE THREAD

**Issue by gskls** [quran/audio.quran.com#99]
Assalamu alaikum . 

whenever i select a hafiz and go to his section . Horizontal scrolling appears .
I found the solution. Please fix it . 

The header's negetive `margin-right` is taking it out of the normal flow . The header's style is -
`.YuRhw1tjUohnA3r6u0TTU {  
           background-size: cover;
           min-height: 350px;
    background: #009faa;
    padding-top: 8rem;
    color: #ffffff;
    padding-bottom: 5rem;
    background-color: #2CA4AB;
    margin-left: -15px;
    margin-right: -15px;
    margin-bottom: 20px;
    `

`margin-right = -15px` is causing the problem . If u wanna keep it just add `width=100%` . That will inshallah solve the problem . 

hope it helps

**Comment by gskls** [comment]
sorry it's fixed in the beta version

**Comment by sabeurthabti** [comment]
no problem. iA we will do a release soon. 
Please feel free to contribute, I am here to help if you need any information.

**Comment by gskls** [comment]
mashallah
